# Generated by Django 4.1.2 on 2023-05-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id_tipo_producto', models.AutoField(db_column='idTipoProducto', primary_key=True, serialize=False)),
                ('desc_tipo_producto', models.CharField(max_length=60)),
            ],
        ),
    ]
