# Generated by Django 4.1.2 on 2023-05-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_tipo_producto_desc_tipo_producto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(db_column='idBoleta', primary_key=True, serialize=False)),
                ('fecha_boleta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=16, unique=True)),
                ('contraseña', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(db_column='idProducto', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Detalle_Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_boleta', models.ForeignKey(db_column='id_boleta', on_delete=django.db.models.deletion.CASCADE, to='venta.boleta')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='venta.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombre_completo_cliente', models.CharField(max_length=60)),
                ('telefono_cliente', models.IntegerField()),
                ('correo_cliente', models.EmailField(max_length=100, unique=True)),
                ('direccion_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='venta.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='venta.cliente'),
        ),
    ]
