# Generated by Django 4.1.2 on 2023-07-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_boleta_usuario_alter_producto_id_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_boleta',
            name='id',
        ),
        migrations.AddField(
            model_name='detalle_boleta',
            name='id_detalle_boleta',
            field=models.AutoField(db_column='idDetalleBoleta', default=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='favorito_producto',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(default=10, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
